app_identifier("com.andrewralon.op1-lfo-hero")
username(ENV["APPLE_ID"])

metadata_path("./fastlane/metadata")
screenshots_path("./fastlane/screenshots")
app_previews_path("./fastlane/app_previews")

automatic_release(false)
submit_for_review(false)
